---

- hosts: ubuntu

  tasks:
  - name: "Sobe o container com um comando especifico"
    community.general.docker_container:
       name: sleepy
       image: ubuntu:latest
       command: ["sleep", "infinity"]

- hosts: webserver

  tasks:
  - name: "Sobe o container com Webserver"
    community.general.docker_container:
       name: nginx-web
       image: nginx:latest
       published_ports: "8080:80"

